export type Day = "fri" | "sat" | "sun";

export interface Artist {
  id: string;
  name: string;
  day: Day;
}

export const ARTISTS: Artist[] = [
  // Friday Apr 17
  { id: "anyma", name: "Anyma", day: "fri" },
  { id: "armin-van-buuren-x-adam-beyer", name: "Armin Van Buuren x Adam Beyer", day: "fri" },
  { id: "arodes", name: "Arodes", day: "fri" },
  { id: "bini", name: "Bini", day: "fri" },
  { id: "blood-orange", name: "Blood Orange", day: "fri" },
  { id: "bob-baker-marionettes", name: "Bob Baker Marionettes", day: "fri" },
  { id: "cachirula-loojan", name: "Cachirula & Loojan", day: "fri" },
  { id: "carolina-durante", name: "Carolina Durante", day: "fri" },
  { id: "central-cee", name: "Central Cee", day: "fri" },
  { id: "chloe-caillet-x-rossi", name: "Chloé Caillet x Rossi.", day: "fri" },
  { id: "cmat", name: "CMAT", day: "fri" },
  { id: "creepy-nuts", name: "Creepy Nuts", day: "fri" },
  { id: "dabeull", name: "Dabeull", day: "fri" },
  { id: "devo", name: "Devo", day: "fri" },
  { id: "dijon", name: "Dijon", day: "fri" },
  { id: "disclosure", name: "Disclosure", day: "fri" },
  { id: "ethel-cain", name: "Ethel Cain", day: "fri" },
  { id: "fakemink", name: "Fakemink", day: "fri" },
  { id: "febuary", name: "Febuary", day: "fri" },
  { id: "fleshwater", name: "Fleshwater", day: "fri" },
  { id: "foster-the-people", name: "Foster The People", day: "fri" },
  { id: "gordo", name: "Gordo", day: "fri" },
  { id: "groove-armada-dj-set", name: "Groove Armada (DJ Set)", day: "fri" },
  { id: "hamdi", name: "Hamdi", day: "fri" },
  { id: "holly-humberstone", name: "Holly Humberstone", day: "fri" },
  { id: "hot-mulligan", name: "Hot Mulligan", day: "fri" },
  { id: "hugel", name: "Hugel", day: "fri" },
  { id: "jessica-brankka", name: "Jessica Brankka", day: "fri" },
  { id: "joost", name: "Joost", day: "fri" },
  { id: "joyce-manor", name: "Joyce Manor", day: "fri" },
  { id: "katseye", name: "Katseye", day: "fri" },
  { id: "kettama", name: "Kettama", day: "fri" },
  { id: "levity", name: "Levity", day: "fri" },
  { id: "lykke-li", name: "Lykke Li", day: "fri" },
  { id: "marlon-hoffstadt", name: "Marlon Hoffstadt", day: "fri" },
  { id: "max-dean-x-luke-dean", name: "Max Dean x Luke Dean", day: "fri" },
  { id: "max-styler", name: "Max Styler", day: "fri" },
  { id: "moby", name: "Moby", day: "fri" },
  { id: "newdad", name: "Newdad", day: "fri" },
  { id: "ninajirachi", name: "Ninajirachi", day: "fri" },
  { id: "nine-inch-noize", name: "Nine Inch Noize", day: "fri" },
  { id: "prospa", name: "Prospa", day: "fri" },
  { id: "sabrina-carpenter", name: "Sabrina Carpenter", day: "fri" },
  { id: "sahar-z", name: "Sahar Z", day: "fri" },
  { id: "sexxy-red", name: "Sexxy Red", day: "fri" },
  { id: "slayyyter", name: "Slayyyter", day: "fri" },
  { id: "teddy-swims", name: "Teddy Swims", day: "fri" },
  { id: "the-two-lips", name: "The Two Lips", day: "fri" },
  { id: "the-xx", name: "The XX", day: "fri" },
  { id: "turnstile", name: "Turnstile", day: "fri" },
  { id: "wednesday", name: "Wednesday", day: "fri" },
  { id: "youna", name: "Youna", day: "fri" },

  // Saturday Apr 18
  { id: "54-ultra", name: "54 Ultra", day: "sat" },
  { id: "addison-rae", name: "Addison Rae", day: "sat" },
  { id: "adriatique", name: "Adriatique", day: "sat" },
  { id: "alex-g", name: "Alex G", day: "sat" },
  { id: "armin-van-buuren-x-adam-beyer-sat", name: "Armin Van Buuren x Adam Beyer", day: "sat" },
  { id: "bedouin", name: "Bedouin", day: "sat" },
  { id: "ben-sterling", name: "Ben Sterling", day: "sat" },
  { id: "bia", name: "Bia", day: "sat" },
  { id: "blondshell", name: "Blondshell", day: "sat" },
  { id: "boys-noize", name: "Boys Noize", day: "sat" },
  { id: "ceremony", name: "Ceremony", day: "sat" },
  { id: "david-byrne", name: "David Byrne", day: "sat" },
  { id: "davido", name: "Davido", day: "sat" },
  { id: "die-spitz", name: "Die Spitz", day: "sat" },
  { id: "dj-snakes-pardon-my-french", name: "DJ Snake's Pardon My French", day: "sat" },
  { id: "ecca-vandal", name: "Ecca Vandal", day: "sat" },
  { id: "freak-slug", name: "Freak Slug", day: "sat" },
  { id: "fujii-kaze", name: "Fujii Kaze", day: "sat" },
  { id: "geese", name: "Geese", day: "sat" },
  { id: "genesi", name: "Genesi", day: "sat" },
  { id: "giveon", name: "Givēon", day: "sat" },
  { id: "interpol", name: "Interpol", day: "sat" },
  { id: "justin-bieber", name: "Justin Bieber", day: "sat" },
  { id: "labrinth", name: "Labrinth", day: "sat" },
  { id: "lambrini-girls", name: "Lambrini Girls", day: "sat" },
  { id: "los-hermanos-flores", name: "Los Hermanos Flores", day: "sat" },
  { id: "luisa-sonza", name: "Luísa Sonza", day: "sat" },
  { id: "mahmut-orhan", name: "Mahmut Orhan", day: "sat" },
  { id: "mind-enterprises", name: "Mind Enterprises", day: "sat" },
  { id: "noga-erez", name: "Noga Erez", day: "sat" },
  { id: "pinkpantheress", name: "PinkPantheress", day: "sat" },
  { id: "rezz", name: "Rezz", day: "sat" },
  { id: "riordan", name: "Riordan", day: "sat" },
  { id: "royel-otis", name: "Royel Otis", day: "sat" },
  { id: "rusowsky", name: "Rusowsky", day: "sat" },
  { id: "sombr", name: "Sómbr", day: "sat" },
  { id: "sosa", name: "Sosa", day: "sat" },
  { id: "swae-lee", name: "Swae Lee", day: "sat" },
  { id: "taemin", name: "Taemin", day: "sat" },
  { id: "the-strokes", name: "The Strokes", day: "sat" },
  { id: "whatmore", name: "Whatmore", day: "sat" },
  { id: "yamagucci", name: "Yamagucci", day: "sat" },
  { id: "zulan", name: "Zulan", day: "sat" },
  { id: "wdusuke-wukimatsu", name: "Wdusuke Wukimatsu", day: "sat" },

  // Sunday Apr 19
  { id: "and-friends", name: "&Friends", day: "sun" },
  { id: "azzecca", name: "Azzecca", day: "sun" },
  { id: "bigbang", name: "Bigbang", day: "sun" },
  { id: "black-flag", name: "Black Flag", day: "sun" },
  { id: "bunt", name: "Bunt.", day: "sun" },
  { id: "carlita-x-josh-baker", name: "Carlita x Josh Baker", day: "sun" },
  { id: "clipse", name: "Clipse", day: "sun" },
  { id: "cobrah", name: "Cobrah", day: "sun" },
  { id: "drain", name: "Drain", day: "sun" },
  { id: "duke-dumont", name: "Duke Dumont", day: "sun" },
  { id: "fka-twigs", name: "FKA Twigs", day: "sun" },
  { id: "flowerovlove", name: "Flowerovlove", day: "sun" },
  { id: "french-police", name: "French Police", day: "sun" },
  { id: "gigi-perez", name: "Gigi Perez", day: "sun" },
  { id: "glitterer", name: "Glitterer", day: "sun" },
  { id: "green-velvet-x-ayybo", name: "Green Velvet x Ayybo", day: "sun" },
  { id: "iggy-pop", name: "Iggy Pop", day: "sun" },
  { id: "jane-remover", name: "Jane Remover", day: "sun" },
  { id: "karol-g", name: "Karol G", day: "sun" },
  { id: "kaskade", name: "Kaskade", day: "sun" },
  { id: "laufey", name: "Laufey", day: "sun" },
  { id: "leyora", name: "Leyora", day: "sun" },
  { id: "little-simz", name: "Little Simz", day: "sun" },
  { id: "los-retros", name: "Los Retros", day: "sun" },
  { id: "major-lazer", name: "Major Lazer", day: "sun" },
  { id: "mochakk", name: "Mochakk", day: "sun" },
  { id: "model-actriz", name: "Model/Actriz", day: "sun" },
  { id: "morat", name: "Morat", day: "sun" },
  { id: "mestiza", name: "Méstiza", day: "sun" },
  { id: "oklou", name: "Oklou", day: "sun" },
  { id: "royksopp-dj-set", name: "Röyksopp (DJ Set)", day: "sun" },
  { id: "roz", name: "Røz", day: "sun" },
  { id: "samia", name: "Samia", day: "sun" },
  { id: "sara-landrys-blood-oath", name: "Sara Landry's Blood Oath", day: "sun" },
  { id: "subtronics", name: "Subtronics", day: "sun" },
  { id: "suicidal-tendencies", name: "Suicidal Tendencies", day: "sun" },
  { id: "the-chats", name: "The Chats", day: "sun" },
  { id: "the-rapture", name: "The Rapture", day: "sun" },
  { id: "tomora", name: "Tomora", day: "sun" },
  { id: "wet-leg", name: "Wet Leg", day: "sun" },
  { id: "whomadewho", name: "WhoMadeWho", day: "sun" },
  { id: "worship", name: "Worship (Sub Focus, Dimension, Culture Shock, 1991)", day: "sun" },
  { id: "young-thug", name: "Young Thug", day: "sun" },
];

export const DAY_LABELS: Record<Day, string> = {
  fri: "Fri Apr 17",
  sat: "Sat Apr 18",
  sun: "Sun Apr 19",
};
