export type Day = "fri" | "sat" | "sun";

export interface Artist {
  id: string;
  name: string;
  day: Day;
  stage?: string;
  startTime?: string; // 24h, e.g. "16:00"; past midnight uses 24+ e.g. "25:00"
  endTime?: string;
}

export const STAGES = [
  "Coachella Stage",
  "Outdoor Theater",
  "Sahara",
  "Gobi",
  "Mojave",
  "Sonora",
  "Yuma",
  "Quasar",
] as const;

export const ARTISTS: Artist[] = [
  // ── Friday Apr 17 ────────────────────────────────────────────
  { id: "anyma", name: "Anyma presents AEden", day: "fri", stage: "Coachella Stage", startTime: "23:50", endTime: "25:00" },
  { id: "armin-van-buuren-x-adam-beyer", name: "Armin Van Buuren x Adam Beyer", day: "fri", stage: "Quasar", startTime: "19:30", endTime: "23:00" },
  { id: "arodes", name: "Arodes", day: "fri", stage: "Yuma", startTime: "14:00", endTime: "15:00" },
  { id: "bini", name: "BINI", day: "fri", stage: "Mojave", startTime: "23:55", endTime: "25:45" },
  { id: "blood-orange", name: "Blood Orange", day: "fri", stage: "Coachella Stage", startTime: "16:00", endTime: "16:45" },
  { id: "bob-baker-marionettes", name: "Bob Baker Marionettes", day: "fri", stage: "Gobi", startTime: "15:55", endTime: "16:35" },
  { id: "cachirula-loojan", name: "Cachirula & Loojan", day: "fri", stage: "Sonora", startTime: "16:10", endTime: "16:55" },
  { id: "carolina-durante", name: "Carolina Durante", day: "fri", stage: "Sonora", startTime: "15:05", endTime: "15:50" },
  { id: "central-cee", name: "Central Cee", day: "fri", stage: "Sahara", startTime: "22:15", endTime: "23:05" },
  { id: "chloe-caillet-x-rossi", name: "Chloé Caillet x Rossi.", day: "fri", stage: "Yuma", startTime: "17:15", endTime: "18:30" },
  { id: "cmat", name: "CMAT", day: "fri", stage: "Mojave", startTime: "16:25", endTime: "17:10" },
  { id: "creepy-nuts", name: "Creepy Nuts", day: "fri", stage: "Gobi", startTime: "21:45", endTime: "22:35" },
  { id: "dabeull", name: "Dabeull", day: "fri", stage: "Outdoor Theater", startTime: "16:35", endTime: "17:20" },
  { id: "devo", name: "Devo", day: "fri", stage: "Mojave", startTime: "18:45", endTime: "19:35" },
  { id: "dijon", name: "Dijon", day: "fri", stage: "Mojave", startTime: "22:40", endTime: "23:30" },
  { id: "disclosure", name: "Disclosure", day: "fri", stage: "Outdoor Theater", startTime: "22:45", endTime: "23:50" },
  { id: "ethel-cain", name: "Ethel Cain", day: "fri", stage: "Outdoor Theater", startTime: "17:50", endTime: "18:40" },
  { id: "fakemink", name: "Fakemink", day: "fri", stage: "Mojave", startTime: "17:35", endTime: "18:20" },
  { id: "febuary", name: "Febuary", day: "fri", stage: "Sonora", startTime: "14:15", endTime: "14:45" },
  { id: "fleshwater", name: "Fleshwater", day: "fri", stage: "Sonora", startTime: "20:35", endTime: "21:20" },
  { id: "foster-the-people", name: "Foster The People", day: "fri", stage: "Coachella Stage", startTime: "17:15", endTime: "18:00" },
  { id: "gordo", name: "Gordo", day: "fri", stage: "Yuma", startTime: "21:00", endTime: "22:15" },
  { id: "groove-armada-dj-set", name: "Groove Armada (DJ Set)", day: "fri", stage: "Yuma", startTime: "22:15", endTime: "23:30" },
  { id: "holly-humberstone", name: "Holly Humberstone", day: "fri", stage: "Mojave", startTime: "20:00", endTime: "20:50" },
  { id: "hot-mulligan", name: "Hot Mulligan", day: "fri", stage: "Sonora", startTime: "21:45", endTime: "22:30" },
  { id: "hugel", name: "HUGEL", day: "fri", stage: "Sahara", startTime: "17:05", endTime: "17:55" },
  { id: "jessica-brankka", name: "Jessica Brankka", day: "fri", stage: "Yuma", startTime: "15:00", endTime: "16:00" },
  { id: "joost", name: "Joost", day: "fri", stage: "Gobi", startTime: "20:30", endTime: "21:20" },
  { id: "joyce-manor", name: "Joyce Manor", day: "fri", stage: "Gobi", startTime: "18:10", endTime: "18:55" },
  { id: "katseye", name: "KATSEYE", day: "fri", stage: "Sahara", startTime: "21:05", endTime: "21:50" },
  { id: "kettama", name: "Kettama", day: "fri", stage: "Yuma", startTime: "23:30", endTime: "25:00" },
  { id: "levity", name: "Levity", day: "fri", stage: "Sahara", startTime: "19:40", endTime: "20:40" },
  { id: "lykke-li", name: "Lykke Li", day: "fri", stage: "Gobi", startTime: "19:20", endTime: "20:05" },
  { id: "marlon-hoffstadt", name: "Marlon Hoffstadt", day: "fri", stage: "Sahara", startTime: "18:15", endTime: "19:15" },
  { id: "max-dean-x-luke-dean", name: "Max Dean x Luke Dean", day: "fri", stage: "Yuma", startTime: "16:00", endTime: "17:15" },
  { id: "max-styler", name: "Max Styler", day: "fri", stage: "Yuma", startTime: "19:45", endTime: "21:00" },
  { id: "moby", name: "Moby", day: "fri", stage: "Mojave", startTime: "21:15", endTime: "22:15" },
  { id: "newdad", name: "NewDad", day: "fri", stage: "Gobi", startTime: "17:00", endTime: "17:45" },
  { id: "ninajirachi", name: "Ninajirachi", day: "fri", stage: "Sonora", startTime: "18:20", endTime: "19:05" },
  { id: "nine-inch-noize", name: "Nine Inch Noize", day: "fri", stage: "Outdoor Theater", startTime: "20:50", endTime: "21:50" },
  { id: "prospa", name: "Prospa", day: "fri", stage: "Yuma", startTime: "18:30", endTime: "19:45" },
  { id: "sabrina-carpenter", name: "Sabrina Carpenter", day: "fri", stage: "Coachella Stage", startTime: "21:50", endTime: "23:05" },
  { id: "sahar-z", name: "Sahar Z", day: "fri", stage: "Yuma", startTime: "13:00", endTime: "14:00" },
  { id: "sexxy-red", name: "Sexyy Red", day: "fri", stage: "Sahara", startTime: "23:30", endTime: "25:15" },
  { id: "slayyyter", name: "Slayyyter", day: "fri", stage: "Gobi", startTime: "23:00", endTime: "23:50" },
  { id: "teddy-swims", name: "Teddy Swims", day: "fri", stage: "Coachella Stage", startTime: "18:30", endTime: "19:15" },
  { id: "the-two-lips", name: "The Two Lips", day: "fri", stage: "Sonora", startTime: "17:15", endTime: "18:00" },
  { id: "the-xx", name: "the xx", day: "fri", stage: "Coachella Stage", startTime: "19:55", endTime: "20:55" },
  { id: "turnstile", name: "Turnstile", day: "fri", stage: "Outdoor Theater", startTime: "19:10", endTime: "20:00" },
  { id: "wednesday", name: "Wednesday", day: "fri", stage: "Sonora", startTime: "19:25", endTime: "20:10" },
  { id: "youna", name: "Youna", day: "fri", stage: "Sahara", startTime: "16:00", endTime: "16:50" },

  // ── Saturday Apr 18 ──────────────────────────────────────────
  { id: "54-ultra", name: "54 Ultra", day: "sat", stage: "Sonora", startTime: "19:10", endTime: "19:50" },
  { id: "addison-rae", name: "Addison Rae", day: "sat", stage: "Outdoor Theater", startTime: "19:50", endTime: "20:40" },
  { id: "adriatique", name: "Adriatique", day: "sat", stage: "Sahara", startTime: "22:35", endTime: "23:35" },
  { id: "alex-g", name: "Alex G", day: "sat", stage: "Mojave", startTime: "18:25", endTime: "19:15" },
  { id: "armin-van-buuren-x-adam-beyer-sat", name: "Armin Van Buuren x Adam Beyer", day: "sat", stage: "Yuma", startTime: "23:00", endTime: "25:00" },
  { id: "bedouin", name: "Bedouin", day: "sat", stage: "Yuma", startTime: "20:15", endTime: "21:30" },
  { id: "ben-sterling", name: "Ben Sterling", day: "sat", stage: "Yuma", startTime: "19:00", endTime: "20:15" },
  { id: "bia", name: "BIA", day: "sat", stage: "Gobi", startTime: "20:25", endTime: "21:15" },
  { id: "blondshell", name: "Blondshell", day: "sat", stage: "Mojave", startTime: "17:15", endTime: "18:00" },
  { id: "boys-noize", name: "Boys Noize", day: "sat", stage: "Yuma", startTime: "21:30", endTime: "23:00" },
  { id: "ceremony", name: "Ceremony", day: "sat", stage: "Sonora", startTime: "18:10", endTime: "18:50" },
  { id: "david-byrne", name: "David Byrne", day: "sat", stage: "Mojave", startTime: "22:10", endTime: "23:10" },
  { id: "davido", name: "Davido", day: "sat", stage: "Coachella Stage", startTime: "16:30", endTime: "17:15" },
  { id: "die-spitz", name: "Die Spitz", day: "sat", stage: "Sonora", startTime: "14:15", endTime: "14:45" },
  { id: "dj-snakes-pardon-my-french", name: "DJ Snake's Pardon My French", day: "sat", stage: "Quasar", startTime: "20:00", endTime: "23:00" },
  { id: "ecca-vandal", name: "Ecca Vandal", day: "sat", stage: "Sonora", startTime: "16:05", endTime: "16:45" },
  { id: "freak-slug", name: "Freak Slug", day: "sat", stage: "Sonora", startTime: "15:05", endTime: "15:45" },
  { id: "fujii-kaze", name: "Fujii Kaze", day: "sat", stage: "Gobi", startTime: "21:40", endTime: "22:30" },
  { id: "geese", name: "Geese", day: "sat", stage: "Gobi", startTime: "18:00", endTime: "18:45" },
  { id: "genesi", name: "GENESI", day: "sat", stage: "Yuma", startTime: "14:00", endTime: "15:15" },
  { id: "giveon", name: "Givēon", day: "sat", stage: "Coachella Stage", startTime: "19:05", endTime: "19:55" },
  { id: "hamdi", name: "Hamdi", day: "sat", stage: "Sahara", startTime: "17:20", endTime: "18:20" },
  { id: "interpol", name: "Interpol", day: "sat", stage: "Mojave", startTime: "19:40", endTime: "20:30" },
  { id: "justin-bieber", name: "Justin Bieber", day: "sat", stage: "Coachella Stage", startTime: "23:10", endTime: "25:00" },
  { id: "labrinth", name: "Labrinth", day: "sat", stage: "Outdoor Theater", startTime: "21:55", endTime: "23:05" },
  { id: "lambrini-girls", name: "Lambrini Girls", day: "sat", stage: "Sonora", startTime: "21:15", endTime: "22:00" },
  { id: "los-hermanos-flores", name: "Los Hermanos Flores", day: "sat", stage: "Outdoor Theater", startTime: "17:05", endTime: "17:50" },
  { id: "luisa-sonza", name: "Luísa Sonza", day: "sat", stage: "Mojave", startTime: "20:55", endTime: "21:45" },
  { id: "mahmut-orhan", name: "Mahmut Orhan", day: "sat", stage: "Yuma", startTime: "17:45", endTime: "19:00" },
  { id: "mind-enterprises", name: "Mind Enterprises", day: "sat", stage: "Sonora", startTime: "17:05", endTime: "17:50" },
  { id: "noga-erez", name: "Noga Erez", day: "sat", stage: "Outdoor Theater", startTime: "15:55", endTime: "16:40" },
  { id: "pinkpantheress", name: "PinkPantheress", day: "sat", stage: "Sahara", startTime: "21:20", endTime: "22:10" },
  { id: "rezz", name: "REZZ", day: "sat", stage: "Sahara", startTime: "24:00", endTime: "25:00" },
  { id: "riordan", name: "Riordan", day: "sat", stage: "Yuma", startTime: "15:15", endTime: "16:30" },
  { id: "royel-otis", name: "Royel Otis", day: "sat", stage: "Gobi", startTime: "19:10", endTime: "20:00" },
  { id: "rusowsky", name: "Rusowsky", day: "sat", stage: "Sonora", startTime: "20:10", endTime: "20:50" },
  { id: "sombr", name: "Sómbr", day: "sat", stage: "Coachella Stage", startTime: "17:45", endTime: "18:30" },
  { id: "sosa", name: "SOSA", day: "sat", stage: "Yuma", startTime: "16:30", endTime: "17:45" },
  { id: "swae-lee", name: "Swae Lee", day: "sat", stage: "Sahara", startTime: "20:05", endTime: "20:55" },
  { id: "taemin", name: "Taemin", day: "sat", stage: "Outdoor Theater", startTime: "18:25", endTime: "19:15" },
  { id: "the-strokes", name: "The Strokes", day: "sat", stage: "Coachella Stage", startTime: "20:40", endTime: "21:55" },
  { id: "whatmore", name: "WHATMORE", day: "sat", stage: "Gobi", startTime: "16:50", endTime: "17:35" },
  { id: "yamagucci", name: "Yamagucci", day: "sat", stage: "Yuma", startTime: "13:00", endTime: "14:00" },
  { id: "zulan", name: "ZULAN", day: "sat", stage: "Sahara", startTime: "16:00", endTime: "17:00" },
  { id: "wdusuke-wukimatsu", name: "YOUSUKE YUKIMATSU", day: "sat", stage: "Sahara", startTime: "18:40", endTime: "19:40" },

  // ── Sunday Apr 19 ─────────────────────────────────────────────
  { id: "and-friends", name: "&Friends", day: "sun", stage: "Yuma", startTime: "14:00", endTime: "15:15" },
  { id: "azzecca", name: "Azzecca", day: "sun", stage: "Yuma", startTime: "15:15", endTime: "16:30" },
  { id: "bigbang", name: "BIGBANG", day: "sun", stage: "Outdoor Theater", startTime: "19:40", endTime: "20:30" },
  { id: "black-flag", name: "Black Flag", day: "sun", stage: "Sonora", startTime: "19:10", endTime: "19:55" },
  { id: "bunt", name: "BUNT.", day: "sun", stage: "Sahara", startTime: "16:00", endTime: "17:00" },
  { id: "carlita-x-josh-baker", name: "Carlita x Josh Baker", day: "sun", stage: "Yuma", startTime: "20:45", endTime: "22:15" },
  { id: "clipse", name: "Clipse", day: "sun", stage: "Coachella Stage", startTime: "17:25", endTime: "18:15" },
  { id: "cobrah", name: "COBRAH", day: "sun", stage: "Gobi", startTime: "20:10", endTime: "21:00" },
  { id: "drain", name: "DRAIN", day: "sun", stage: "Sonora", startTime: "17:10", endTime: "17:50" },
  { id: "duke-dumont", name: "Duke Dumont", day: "sun", stage: "Sahara", startTime: "20:05", endTime: "21:05" },
  { id: "fka-twigs", name: "FKA twigs", day: "sun", stage: "Outdoor Theater", startTime: "21:25", endTime: "22:25" },
  { id: "flowerovlove", name: "Flowerovlove", day: "sun", stage: "Gobi", startTime: "15:30", endTime: "16:10" },
  { id: "french-police", name: "French Police", day: "sun", stage: "Sonora", startTime: "18:10", endTime: "18:50" },
  { id: "gigi-perez", name: "Gigi Perez", day: "sun", stage: "Mojave", startTime: "19:05", endTime: "19:55" },
  { id: "glitterer", name: "Glitterer", day: "sun", stage: "Sonora", startTime: "14:15", endTime: "14:50" },
  { id: "green-velvet-x-ayybo", name: "Green Velvet x AYYBO", day: "sun", stage: "Yuma", startTime: "22:15", endTime: "24:00" },
  { id: "iggy-pop", name: "Iggy Pop", day: "sun", stage: "Mojave", startTime: "21:35", endTime: "22:25" },
  { id: "jane-remover", name: "Jane Remover", day: "sun", stage: "Sonora", startTime: "16:10", endTime: "16:50" },
  { id: "karol-g", name: "Karol G", day: "sun", stage: "Coachella Stage", startTime: "22:25", endTime: "24:00" },
  { id: "kaskade", name: "Kaskade", day: "sun", stage: "Sahara", startTime: "22:55", endTime: "23:55" },
  { id: "laufey", name: "Laufey", day: "sun", stage: "Outdoor Theater", startTime: "18:05", endTime: "18:55" },
  { id: "leyora", name: "LE YORA", day: "sun", stage: "Yuma", startTime: "13:00", endTime: "14:00" },
  { id: "little-simz", name: "Little Simz", day: "sun", stage: "Coachella Stage", startTime: "16:10", endTime: "16:55" },
  { id: "los-retros", name: "Los Retros", day: "sun", stage: "Sonora", startTime: "15:10", endTime: "15:50" },
  { id: "major-lazer", name: "Major Lazer", day: "sun", stage: "Coachella Stage", startTime: "18:50", endTime: "19:50" },
  { id: "mochakk", name: "Mochakk", day: "sun", stage: "Sahara", startTime: "17:20", endTime: "18:20" },
  { id: "model-actriz", name: "Model/Actriz", day: "sun", stage: "Sonora", startTime: "20:20", endTime: "21:05" },
  { id: "morat", name: "Morat", day: "sun", stage: "Gobi", startTime: "17:45", endTime: "18:30" },
  { id: "mestiza", name: "Méstiza", day: "sun", stage: "Yuma", startTime: "16:30", endTime: "17:45" },
  { id: "oklou", name: "Oklou", day: "sun", stage: "Mojave", startTime: "20:20", endTime: "21:10" },
  { id: "royksopp-dj-set", name: "Röyksopp (DJ Set)", day: "sun", stage: "Yuma", startTime: "19:15", endTime: "20:45" },
  { id: "roz", name: "Røz", day: "sun", stage: "Sonora", startTime: "21:30", endTime: "22:20" },
  { id: "samia", name: "Samia", day: "sun", stage: "Mojave", startTime: "16:35", endTime: "17:25" },
  { id: "sara-landrys-blood-oath", name: "Sara Landry's Blood Oath", day: "sun", stage: "Quasar", startTime: "19:00", endTime: "22:00" },
  { id: "subtronics", name: "Subtronics", day: "sun", stage: "Sahara", startTime: "21:30", endTime: "22:30" },
  { id: "suicidal-tendencies", name: "Suicidal Tendencies", day: "sun", stage: "Mojave", startTime: "17:50", endTime: "18:40" },
  { id: "the-chats", name: "The Chats", day: "sun", stage: "Gobi", startTime: "16:35", endTime: "17:20" },
  { id: "the-rapture", name: "The Rapture", day: "sun", stage: "Gobi", startTime: "18:55", endTime: "19:45" },
  { id: "tomora", name: "Tomora", day: "sun", stage: "Gobi", startTime: "21:25", endTime: "22:25" },
  { id: "wet-leg", name: "Wet Leg", day: "sun", stage: "Outdoor Theater", startTime: "16:40", endTime: "17:30" },
  { id: "whomadewho", name: "WhoMadeWho", day: "sun", stage: "Yuma", startTime: "17:45", endTime: "19:15" },
  { id: "worship", name: "Worship", day: "sun", stage: "Sahara", startTime: "18:40", endTime: "19:40" },
  { id: "young-thug", name: "Young Thug", day: "sun", stage: "Coachella Stage", startTime: "20:30", endTime: "21:20" },
];

export const DAY_LABELS: Record<Day, string> = {
  fri: "Fri Apr 17",
  sat: "Sat Apr 18",
  sun: "Sun Apr 19",
};

/** Convert "HH:MM" string (with 24+ for past midnight) to minutes since midnight */
export function timeToMinutes(t: string): number {
  const [h, m] = t.split(":").map(Number);
  return h * 60 + m;
}
